version: '3.9'
services:
  hiflow3v3:
    build: .
    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      # - <host>:<container>
      - ./hiflow:/home/hiflow3

